// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJapFmgBlXLHOT9rvL5VOuPOC9y3QbtxU',
    appId: '1:277752939287:web:f9baebfdc664c3f2482d52',
    messagingSenderId: '277752939287',
    projectId: 'flutter-chat-17bb4',
    authDomain: 'flutter-chat-17bb4.firebaseapp.com',
    storageBucket: 'flutter-chat-17bb4.appspot.com',
    measurementId: 'G-T8DBEB337Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFbVwKvFDRXtxR3By06REuPNwqxC6qEqc',
    appId: '1:277752939287:android:052726bfd54bc32e482d52',
    messagingSenderId: '277752939287',
    projectId: 'flutter-chat-17bb4',
    storageBucket: 'flutter-chat-17bb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVJUsTTZUHvYZgF4JxgHw_HqLScADl08s',
    appId: '1:277752939287:ios:7f4fed8b53a6c00f482d52',
    messagingSenderId: '277752939287',
    projectId: 'flutter-chat-17bb4',
    storageBucket: 'flutter-chat-17bb4.appspot.com',
    iosClientId: '277752939287-rhkv0v9dtj0ilf8q6smm7m698jhn19vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVJUsTTZUHvYZgF4JxgHw_HqLScADl08s',
    appId: '1:277752939287:ios:7f4fed8b53a6c00f482d52',
    messagingSenderId: '277752939287',
    projectId: 'flutter-chat-17bb4',
    storageBucket: 'flutter-chat-17bb4.appspot.com',
    iosClientId: '277752939287-rhkv0v9dtj0ilf8q6smm7m698jhn19vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
